import '@/utils/auth.js'
import './index.css'
import axios from '@/utils/request.js'
import editor from '@/utils/editor.js'
import {Myalert} from '@/utils/alert.js'
import serialize from 'form-serialize'
import '@/utils/channels.js'